# Generated by Django 5.0 on 2023-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UT', 'Utopic'), ('DY', 'Dystopic')], default='UT', max_length=2)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
