# Generated by Django 5.0 on 2023-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='votes',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
