# Generated by Django 5.0 on 2023-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0002_rename_votes_suggestion_downvotes_suggestion_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='downvotes',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('UT', 'Utopisch'), ('DY', 'Dystopisch')], default='UT', max_length=2),
        ),
    ]
