# Generated by Django 5.0 on 2023-12-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0005_suggestion_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingoproject',
            name='name',
        ),
    ]
